name: 10 - Controlling the Execution Flow

on:
  workflow_dispatch:
    inputs:
      pass-unit-tests:
        description: 'Set to true to pass unit tests'
        required: true
        default: "true"
      pass-e2e-tests:
        description: 'Set to true to pass e2e tests'
        required: true
        default: "false"

jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - name: Lint and Build
        run: echo "Linting and Building..."
  unit-tests:
    needs: lint-build
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs['pass-unit-tests'] == 'true' }}
    steps:
      - name: Run Unit Tests
        run: echo "Running Unit Tests..."
  deploy-non-prod:
    needs: [unit-tests, lint-build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying non-prod..."
  e2e-tests:
    needs: deploy-non-prod
    runs-on: ubuntu-latest
    steps:
      - name: Run E2E Tests
        run: echo "Running E2E Tests..."
      - name: Check E2E Test Result
        if: ${{ github.event.inputs['pass-e2e-tests'] != 'true' }}
        run: |
          echo "E2E tests failed!"
          exit 1
  deploy-prod:
    needs: [e2e-tests, deploy-non-prod]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production
        run: echo "Deploying to Production..."