name: 16 - Environments

run-name: 16 - Working with Environments | env - ${{ github.event.inputs.target-env }}

on:
  workflow_dispatch:
    inputs:
      target-env:
        description: 'Environment to deploy to'
        type: environment
        required: true


jobs:
  echo:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-env }}
    env:
      myvar: ${{ vars.MY_VAR || 'default-value' }}
    steps:
      - name: Show environment
        run: | 
          echo "Deploying to environment: ${{ env.myvar }}"

  echo2:
    runs-on: ubuntu-latest
    needs: echo
    environment: ${{ inputs.target-env == 'prod' && 'dev' || 'prod' }}
    env:
      myvar: ${{ vars.MY_VAR || 'default-value' }}
    steps:
      - name: Show environment
        run: | 
          echo "Deploying to environment: ${{ env.myvar }}"

  echo3:
    runs-on: ubuntu-latest
    needs: echo2
    steps:
      - name: Show environment
        run: | 
          echo "Not deploying to any environment"

  echo4:
    runs-on: ubuntu-latest
    needs: echo3
    environment: prod
    steps:
      - name: Show environment
        run: | 
          echo "Again to dev"

  echo5:
    runs-on: ubuntu-latest
    needs: echo2
    environment: prod
    steps:
      - name: Show environment
        run: | 
          echo "Again to dev"
