name: 17 - 1 - Custom Actions - Composite

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 04-using-actions/react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Cache Node and NPM dependencies
        uses: ./.github/actions/composite-cache-dependencies
        with:
          node-version: 22.x
          working-dir: 04-using-actions/react-app
      - name: Test
        run: npm run test

      - name: Build
        run: npm run build