name: Quick Pull Test

on:
  workflow_dispatch:

env:
  REGISTRY: artemdefualtregistry.azurecr.io
  IMAGE_NAME: azure-tools

jobs:
  container-test-job:
    runs-on: self-hosted
    container:
      image: devops-tools:latest
    #   credentials:
    #     username: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
    #     password: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
      options: --cpus 1
    steps:
      - name: Check container environment
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)

      - name: Checkout
        uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Test Azure CLI
        run: az account show